# Generated by Django 5.0.4 on 2024-04-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
    ]
