# Generated by Django 5.0.4 on 2024-05-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_property_owner'),
        ('api', '0003_alter_unavailability_comment_and_more'),
    ]

    operations = [
    ]
