# Generated by Django 5.0.4 on 2024-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_MCD-V1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.TextField(),
        ),
    ]
