# Generated by Django 5.0.4 on 2024-05-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ext_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_image/'),
        ),
    ]
